Use shared functions from common submodule also in replication tests

diff --git a/test/run-openshift b/test/run-openshift
--- a/test/run-openshift
+++ b/test/run-openshift
@@ -6,28 +6,16 @@
 # The image has to be available before this script is executed.
 #
 
+THISDIR=$(dirname ${BASH_SOURCE[0]})
+TEMPLATES="$THISDIR/examples/petset"
+
+source "$THISDIR"/test-lib-openshift.sh
+
 set -exo nounset
 
 test -n "${IMAGE_NAME-}" || false 'make sure $IMAGE_NAME is defined'
-
-function prepare_oc_client() {
-  # Prepare oc command
-  if [[ ! -d ../openshift-client/ ]]; then
-    OC_RELEASE=$(curl -s https://api.github.com/repos/openshift/origin/releases | grep "browser_download_url" | grep "openshift-origin-client" | grep "linux-64bit" | sort | grep -E "v[0-9]+\.[0-9]+\.[0-9]+/"| tail -n 1 | sed -e 's|"browser_download_url": ||' | tr -d ' "')
-
-    curl -L ${OC_RELEASE} | tar xz
-    mv ./openshift-origin-client-tools-* ../openshift-client
-  fi
-  export PATH=${PATH}:`pwd`/../openshift-client/
-}
-prepare_oc_client
-
-function cleanup() {
-  echo "Stopping and removing OpenShift cluster..."
-  oc delete project --all
-  oc cluster down
-}
-trap cleanup EXIT SIGINT
+test -n "${VERSION-}" || false 'make sure $VERSION is defined'
+test -n "${OS-}" || false 'make sure $OS is defined'
 
 function print_logs() {
   oc get all
@@ -39,52 +27,95 @@ function print_logs() {
 }
 trap print_logs ERR
 
-# Start OpenShift cluster
-[ -d openshift.pv ] || mkdir openshift.pv
-oc cluster up --host-pv-dir=$(pwd)/openshift.pv
+function check_mongodb_os_service_connection() {
+  local util_image_name=$1 ; shift
+  local service_name=$1 ; shift
+  local user=$1 ; shift
+  local pass=$1 ; shift
+  local database=$1 ; shift
+  local pod_ip=$(ct_os_get_service_ip ${service_name})
 
-# Prepare image - add tag different than :latest
-# With :latest default imagePullPolicy is Always
-# https://docs.openshift.com/enterprise/3.2/dev_guide/managing_images.html#image-pull-policy
-docker tag ${IMAGE_NAME} ${IMAGE_NAME}:test-openshift
-IMAGE_NAME=${IMAGE_NAME}:test-openshift
+  : "  Service ${service_name} check ..."
 
-#
-# General functions
-#
+  local cmd="source /usr/share/container-scripts/mongodb/common.sh; wait_for_mongo_up mongodb://${pod_ip}/${database}; mongo mongodb://${pod_ip}/${database} -u ${user} -p ${pass}"
 
-# wait_for_ready_pods wait till number of pods with label get ready
-function wait_for_ready_pods() {
-  local label="$1"
-  local count="$2"
-  for i in $(seq 30); do
-    if [[ "$(oc get pods --no-headers=true -l${label} | grep "1/1" | wc -l)" -eq ${count} ]]; then
-      return 0
-    fi
-    echo "Waiting for ${count} ready pods labeled with '${label}'..."
-    sleep 20
-  done
+  echo -n "Waiting for ${service_name} service becoming ready ..."
+  if docker run --rm ${util_image_name} bash -c "${cmd}"; then
+    echo " PASS"
+    return 0
+  fi
+  echo " FAIL"
   return 1
 }
 
-# Deploy MongoDB clustered application
-USER=user
-PASS=pass
-ADMIN_PASS=adminPass
-DB=db
+function wait_statefulsets_ready() {
+  local pod_prefix="${1}" ; shift
+  local timeout="${1}" ; shift
+  SECONDS=0
+  echo -n "Waiting for ${pod_prefix} pod becoming ready ..."
+  while ! test "$(oc get statefulsets --no-headers 2>/dev/null \
+                 | grep "^${pod_prefix}" | awk '$2==$3 {print "ready"}')" == "ready" ; do
+    echo -n "."
+    [ ${SECONDS} -gt ${timeout} ] && echo " FAIL" && return 1
+    sleep 3
+  done
+  echo " DONE"
+}
 
-oc new-project petset-example
-oc new-app --file=../examples/petset/mongodb-petset-persistent.yaml -p MONGODB_USER=${USER} -p MONGODB_PASSWORD=${PASS} -p MONGODB_DATABASE=${DB} -p MONGODB_ADMIN_PASSWORD=${ADMIN_PASS} -p MONGODB_IMAGE=${IMAGE_NAME} -p VOLUME_CAPACITY=500M
+function test_mongodb_pure_image() {
+  local image_name=$1
+  local image_name_no_namespace=${image_name##*/}
+  local service_name=${image_name_no_namespace}
 
-wait_for_ready_pods "app=mongodb-petset-replication" 3
-wait_for_ready_pods "openshift.io/deployer-pod-for.name" 0
+  ct_os_new_project
+  ct_os_upload_image "${image_name}"
+  # Create a specific imagestream tag for the image so that oc cannot use anything else
+  ct_os_upload_image "${image_name}" "$image_name_no_namespace:testing"
 
-host="$(oc get endpoints mongodb --no-headers | tr -s ' ' | cut -f2 -d' ')/admin?replicaSet=rs0"
+  ct_os_deploy_pure_image "$image_name_no_namespace:testing" \
+                          --name "${service_name}" \
+                          --env MONGODB_ADMIN_PASSWORD=test
 
-docker exec origin kubectl run --attach --restart=Never mongodb-test --image ${IMAGE_NAME} --env="MONGODB_ADMIN_PASSWORD=${ADMIN_PASS}" --command -- bash -c "set -x
+  ct_os_wait_pod_ready "${service_name}" 60
+  check_mongodb_os_service_connection "${image_name}" "${service_name}" admin test admin
+
+  ct_os_delete_project
+}
+
+function test_mongodb_replication() {
+  local image_name=${1:-centos/mongodb-${VERSION//\.}-centos7}
+  local image_name_no_namespace=${image_name##*/}
+  local service_name=${image_name_no_namespace}
+
+  ADMIN_PASS=adminPass
+
+  ct_os_new_project
+  ct_os_upload_image "${image_name}" "mongodb:$VERSION"
+
+  ct_os_deploy_template_image "$TEMPLATES/mongodb-petset-persistent.yaml" \
+                              MONGODB_IMAGE="$image_name" \
+                              MONGODB_SERVICE_NAME="${service_name}" \
+                              MONGODB_USER=testu \
+                              MONGODB_PASSWORD=testp \
+                              MONGODB_DATABASE=testdb \
+                              MONGODB_ADMIN_PASSWORD=${ADMIN_PASS} \
+                              VOLUME_CAPACITY=500M
+
+  wait_statefulsets_ready "${service_name}" 300
+  check_mongodb_os_service_connection "${image_name}" "${service_name}" admin ${ADMIN_PASS} admin
+  check_mongodb_os_service_connection "${image_name}" "${service_name}" testu testp testdb
+
+  oc exec $(ct_os_get_pod_name mongodb | head -n 1) -- bash -c 'set -x
 . /usr/share/container-scripts/mongodb/common.sh
 . /usr/share/container-scripts/mongodb/test-functions.sh
-wait_for_mongo_up '${host}'
-wait_replicaset_members '${host}' 3
-insert_and_wait_for_replication '${host}' '{a:5, b:10}'"
+wait_replicaset_members "$(replset_addr admin)" 3
+insert_and_wait_for_replication "$(replset_addr admin)" "{a:5, b:10}"'
+
+  ct_os_delete_project
+}
+
+ct_os_cluster_up
+test_mongodb_pure_image "${IMAGE_NAME}"
+test_mongodb_replication "${IMAGE_NAME}"
+ct_os_cluster_down
 
