Add tests for image streams and refactor tests to work with remote OCP4 cluster

diff --git a/test/run-openshift-local-cluster b/test/run-openshift-local-cluster
--- a/test/run-openshift-local-cluster
+++ b/test/run-openshift-local-cluster
@@ -12,11 +12,11 @@ TEMPLATES="$THISDIR/examples/petset"
 source "$THISDIR"/test-lib-openshift.sh
 source ${THISDIR}/test-lib-mongodb.sh
 
-set -exo nounset
+set -eo nounset
 
-test -n "${IMAGE_NAME-}" || false 'make sure $IMAGE_NAME is defined'
-test -n "${VERSION-}" || false 'make sure $VERSION is defined'
-test -n "${OS-}" || false 'make sure $OS is defined'
+trap ct_os_cleanup EXIT SIGINT
+
+ct_os_check_compulsory_vars
 
 ct_os_enable_print_logs
 
@@ -103,19 +103,34 @@ test_mongodb_pure_image "${IMAGE_NAME}"
 test_mongodb_replication "${IMAGE_NAME}"
 
 # test with the just built image and an integrated template
+echo "Running test_mongodb_integration with ${IMAGE_NAME}"
 test_mongodb_integration "${IMAGE_NAME}" "${VERSION}" mongodb
 
 # test with a released image and an integrated template
+# ignore possible failure of this test for centos images
+fail_not_released=true
 if [ "${OS}" == "rhel7" ] ; then
-  PUBLIC_IMAGE_NAME=${PUBLIC_IMAGE_NAME:-${REGISTRY:-registry.access.redhat.com/}rhscl/${BASE_IMAGE_NAME}-${VERSION//./}-rhel7}
+  PUBLIC_IMAGE_NAME=${PUBLIC_IMAGE_NAME:-${REGISTRY:-registry.redhat.io/}rhscl/${BASE_IMAGE_NAME}-${VERSION//./}-rhel7}
 else
   PUBLIC_IMAGE_NAME=${PUBLIC_IMAGE_NAME:-${REGISTRY:-}centos/${BASE_IMAGE_NAME}-${VERSION//./}-centos7}
+  fail_not_released=false
 fi
 
-export CT_SKIP_UPLOAD_IMAGE=true
-test_mongodb_integration mongodb "${VERSION}" "${PUBLIC_IMAGE_NAME}"
+# Try pulling the image first to see if it is accessible
+if docker pull "${PUBLIC_IMAGE_NAME}"; then
+  echo "Running test_mongodb_integration with ${PUBLIC_IMAGE_NAME}"
+  test_mongodb_integration "${PUBLIC_IMAGE_NAME}" "${VERSION}" mongodb
+else
+  echo "Warning: ${PUBLIC_IMAGE_NAME} could not be downloaded via 'docker'"
+  ! $fail_not_released || false "ERROR: Failed to pull image"
+fi
+
+# Check the imagestream
+test_mongodb_imagestream
 
 OS_TESTSUITE_RESULT=0
 
 ct_os_cluster_down
+
+# vim: set tabstop=2:shiftwidth=2:expandtab:
 
