Use shared functions from common submodule also in replication tests (#275)
* Use shared functions from common submodule also in replication
tests

* - Fix mounting option in s2i_mount test
- Increase timeout (older versions are slower)

* Wait longer for replication to be ready

Include update functions from test-lib-openshift.sh (separate PR)

* Update test functions from PR in commons

* Use functions from common + remove local copy

* Update common submodule

* Wait for each pod to be ready

* Always tag image with VERSION tag

diff --git a/test/run-openshift b/test/run-openshift
--- a/test/run-openshift
+++ b/test/run-openshift
@@ -6,85 +6,99 @@
 # The image has to be available before this script is executed.
 #
 
+THISDIR=$(dirname ${BASH_SOURCE[0]})
+TEMPLATES="$THISDIR/examples/petset"
+
+source "$THISDIR"/test-lib-openshift.sh
+
 set -exo nounset
 
 test -n "${IMAGE_NAME-}" || false 'make sure $IMAGE_NAME is defined'
+test -n "${VERSION-}" || false 'make sure $VERSION is defined'
+test -n "${OS-}" || false 'make sure $OS is defined'
 
-function prepare_oc_client() {
-  # Prepare oc command
-  if [[ ! -d ../openshift-client/ ]]; then
-    OC_RELEASE=$(curl -s https://api.github.com/repos/openshift/origin/releases | grep "browser_download_url" | grep "openshift-origin-client" | grep "linux-64bit" | sort | grep -E "v[0-9]+\.[0-9]+\.[0-9]+/"| tail -n 1 | sed -e 's|"browser_download_url": ||' | tr -d ' "')
+ct_os_enable_print_logs
 
-    curl -L ${OC_RELEASE} | tar xz
-    mv ./openshift-origin-client-tools-* ../openshift-client
-  fi
-  export PATH=${PATH}:`pwd`/../openshift-client/
-}
-prepare_oc_client
+function check_mongodb_os_service_connection() {
+  local util_image_name=$1 ; shift
+  local service_name=$1 ; shift
+  local user=$1 ; shift
+  local pass=$1 ; shift
+  local database=$1 ; shift
+  local timeout=${1:-60} ; shift || :
+  local pod_ip=$(ct_os_get_service_ip ${service_name})
 
-function cleanup() {
-  echo "Stopping and removing OpenShift cluster..."
-  oc delete project --all
-  oc cluster down
-}
-trap cleanup EXIT SIGINT
+  : "  Service ${service_name} check ..."
 
-function print_logs() {
-  oc get all
-  while read pod_info; do
-    pod=$(echo ${pod_info} | tr -s ' ' | cut -f1 -d' ')
-    echo "INFO: printing logs for pod ${pod}"
-    oc logs ${pod}
-  done < <(oc get pods --no-headers=true)
-}
-trap print_logs ERR
+  local cmd="mongo ${pod_ip}/${database} -u ${user} -p${pass} --eval 'quit()'"
+  SECONDS=0
 
-# Start OpenShift cluster
-[ -d openshift.pv ] || mkdir openshift.pv
-oc cluster up --host-pv-dir=$(pwd)/openshift.pv
-
-# Prepare image - add tag different than :latest
-# With :latest default imagePullPolicy is Always
-# https://docs.openshift.com/enterprise/3.2/dev_guide/managing_images.html#image-pull-policy
-docker tag ${IMAGE_NAME} ${IMAGE_NAME}:test-openshift
-IMAGE_NAME=${IMAGE_NAME}:test-openshift
-
-#
-# General functions
-#
-
-# wait_for_ready_pods wait till number of pods with label get ready
-function wait_for_ready_pods() {
-  local label="$1"
-  local count="$2"
-  for i in $(seq 30); do
-    if [[ "$(oc get pods --no-headers=true -l${label} | grep "1/1" | wc -l)" -eq ${count} ]]; then
-      return 0
-    fi
-    echo "Waiting for ${count} ready pods labeled with '${label}'..."
-    sleep 20
+  echo -n "Waiting for ${service_name} service becoming ready ..."
+  while ! docker run --rm ${util_image_name} bash -c "${cmd}" ; do
+    echo -n "."
+    [ ${SECONDS} -gt ${timeout} ] && echo " FAIL" && return 1
+    sleep 3
   done
-  return 1
+  echo " PASS"
+  return 0
 }
 
-# Deploy MongoDB clustered application
-USER=user
-PASS=pass
-ADMIN_PASS=adminPass
-DB=db
+function test_mongodb_pure_image() {
+  local image_name=$1
+  local image_name_no_namespace=${image_name##*/}
+  local service_name=${image_name_no_namespace}
 
-oc new-project petset-example
-oc new-app --file=../examples/petset/mongodb-petset-persistent.yaml -p MONGODB_USER=${USER} -p MONGODB_PASSWORD=${PASS} -p MONGODB_DATABASE=${DB} -p MONGODB_ADMIN_PASSWORD=${ADMIN_PASS} -p MONGODB_IMAGE=${IMAGE_NAME} -p VOLUME_CAPACITY=500M
+  ct_os_new_project
+  ct_os_upload_image "${image_name}"
+  # Create a specific imagestream tag for the image so that oc cannot use anything else
+  ct_os_upload_image "${image_name}" "$image_name_no_namespace:testing"
 
-wait_for_ready_pods "app=mongodb-petset-replication" 3
-wait_for_ready_pods "openshift.io/deployer-pod-for.name" 0
+  ct_os_deploy_pure_image "$image_name_no_namespace:testing" \
+                          --name "${service_name}" \
+                          --env MONGODB_ADMIN_PASSWORD=test
 
-host="$(oc get endpoints mongodb --no-headers | tr -s ' ' | cut -f2 -d' ')/admin?replicaSet=rs0"
+  ct_os_wait_pod_ready "${service_name}" 60
+  check_mongodb_os_service_connection "${image_name}" "${service_name}" admin test admin 120
 
-docker exec origin kubectl run --attach --restart=Never mongodb-test --image ${IMAGE_NAME} --env="MONGODB_ADMIN_PASSWORD=${ADMIN_PASS}" --command -- bash -c "set -x
+  ct_os_delete_project
+}
+
+function test_mongodb_replication() {
+  local image_name=${1:-centos/mongodb-${VERSION//\.}-centos7}
+  local image_name_no_namespace=${image_name##*/}
+  local service_name=${image_name_no_namespace}
+
+  ADMIN_PASS=adminPass
+
+  ct_os_new_project
+  docker tag "${image_name}" "${image_name}:$VERSION"
+
+  ct_os_deploy_template_image "$TEMPLATES/mongodb-petset-persistent.yaml" \
+                              MONGODB_IMAGE="${image_name}:$VERSION" \
+                              MONGODB_SERVICE_NAME="${service_name}" \
+                              MONGODB_USER=testu \
+                              MONGODB_PASSWORD=testp \
+                              MONGODB_DATABASE=testdb \
+                              MONGODB_ADMIN_PASSWORD=${ADMIN_PASS} \
+                              VOLUME_CAPACITY=500M
+
+  ct_os_wait_rc_ready "${service_name}" 600
+  for pod in $(ct_os_get_pod_name mongodb); do
+    ct_os_wait_pod_ready $pod 300
+  done
+  check_mongodb_os_service_connection "${image_name}:$VERSION" "${service_name}" admin ${ADMIN_PASS} admin
+  check_mongodb_os_service_connection "${image_name}:$VERSION" "${service_name}" testu testp testdb
+
+  ct_os_run_in_pod $(ct_os_get_pod_name mongodb | head -n 1) bash -c 'set -x
 . /usr/share/container-scripts/mongodb/common.sh
 . /usr/share/container-scripts/mongodb/test-functions.sh
-wait_for_mongo_up '${host}'
-wait_replicaset_members '${host}' 3
-insert_and_wait_for_replication '${host}' '{a:5, b:10}'"
+insert_and_wait_for_replication "$(replset_addr admin)" "{a:5, b:10}"'
+
+  ct_os_delete_project
+}
+
+ct_os_cluster_up
+test_mongodb_pure_image "${IMAGE_NAME}"
+test_mongodb_replication "${IMAGE_NAME}"
+ct_os_cluster_down
 
