Add help.1 file (#229)
Atomic CLI tool shows groff formatted man page if called by atomic help <img>, so all images should support it.
Currently the man page is generated outside of the build system by pandoc -s -f markdown -t man.
Let's incluce README.md in a topic directory, to allow more existing in one image

diff --git a/3.2/test/run b/3.2/test/run
--- a/3.2/test/run
+++ b/3.2/test/run
@@ -317,6 +317,31 @@ unixSocketPrefix = /var/lib/mongodb" > $config_file
     echo "  Success!"
 }
 
+run_doc_test() {
+  local tmpdir=$(mktemp -d)
+  local f
+  echo "  Testing documentation in the container image"
+  # Extract the help files from the container
+  for f in /usr/share/container-scripts/mongodb/README.md help.1 ; do
+    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/$(basename ${f})
+    # Check whether the files include some important information
+    for term in MONGODB_ADMIN_PASSWORD volume ; do
+      if ! cat ${tmpdir}/$(basename ${f}) | grep -q -e "${term}" ; then
+        echo "ERROR: File /${f} does not include '${term}'."
+        return 1
+      fi
+    done
+  done
+  # Check whether the files use the correct format
+  if ! file ${tmpdir}/help.1 | grep -q roff ; then
+    echo "ERROR: /help.1 is not in troff or groff format"
+    return 1
+  fi
+  echo "  Success!"
+  echo
+}
+
+
 # Tests.
 run_configuration_tests
 USER="user1" PASS="pass1" DB="test_db" ADMIN_PASS="r00t" run_tests admin
@@ -324,3 +349,4 @@ USER="user1" PASS="pass1" DB="test_db" ADMIN_PASS="r00t" run_tests admin
 CONTAINER_ARGS="-u 12345" USER="user1" PASS="pass1" DB="test_db" ADMIN_PASS="r00t" run_tests admin_altuid
 run_change_password_test
 run_mount_config_test
+run_doc_test
